services:
  api:
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '8000:8000'
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@postgres:5432/musicApp
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17.3
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musicApp
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
